# Generated by Django 4.1 on 2022-09-27 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_tasklist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 17, 0, 8, 614211, tzinfo=datetime.timezone.utc)),
        ),
    ]
