# Generated by Django 4.1 on 2022-09-28 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_tasklist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 16, 14, 53, 779928, tzinfo=datetime.timezone.utc)),
        ),
    ]
