# Generated by Django 4.1 on 2022-09-28 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_alter_tasklist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 29, 0, 3, 16, 990252)),
        ),
    ]
